# Generated by Django 5.2.14 on 2026-05-13 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('project_type', models.CharField(choices=[('static', 'Static'), ('django', 'Django'), ('flask', 'Flask'), ('node', 'Node'), ('php', 'PHP'), ('wordpress', 'WordPress'), ('mysql_only', 'MySQL only')], db_index=True, default='static', max_length=32)),
                ('subdomain', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('deploying', 'Deploying'), ('running', 'Running'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
