# Generated by Django 5.2.14 on 2026-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_hostname',
            field=models.CharField(blank=True, db_index=True, help_text='Optional public hostname (e.g. www.example.com) for this project.', max_length=253, null=True, unique=True),
        ),
    ]
