# Generated by Django 5.0.14 on 2026-05-16 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_custom_domain_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_deleted'], name='project_owner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted', 'status'], name='project_status_active_idx'),
        ),
    ]
