# Generated by Django 5.2.14 on 2026-05-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsubfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOverview',
            fields=[
            ],
            options={
                'verbose_name': 'Website Overview',
                'verbose_name_plural': 'Website Overview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
