# Generated by Django 5.2.14 on 2026-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_promomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flask_port',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Port on the flask-runner container (7000-7999). Null = not a running Flask project.', null=True, unique=True),
        ),
    ]
