# Generated by Django 5.2.14 on 2026-05-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_report', to='uploads.projectupload'),
        ),
    ]
