# Generated by Django 5.2.14 on 2026-05-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_slug', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], db_index=True, default='free', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
