# Generated by Django 5.2.14 on 2026-05-27 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_test_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_slug', models.CharField(choices=[('free', 'Free'), ('test_plan', 'Starter Trial'), ('launch_lite', 'Launch Lite'), ('starter_cloud', 'Starter Cloud'), ('wordpress_pro', 'WordPress Pro'), ('business_cloud', 'Business Cloud'), ('agency_turbo', 'Agency Turbo'), ('performance_max', 'Performance Max')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('current_period_end', models.DateTimeField()),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_addons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
