# Generated by Django 5.2.14 on 2026-05-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_plan_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('test_plan', 'Starter Trial'), ('launch_lite', 'Launch Lite'), ('starter_cloud', 'Starter Cloud'), ('wordpress_pro', 'WordPress Pro'), ('business_cloud', 'Business Cloud'), ('agency_turbo', 'Agency Turbo'), ('performance_max', 'Performance Max'), ('flask_addon', 'Flask Add-on')], default='launch_lite', max_length=32),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='plan_slug',
            field=models.CharField(choices=[('free', 'Free'), ('test_plan', 'Starter Trial'), ('launch_lite', 'Launch Lite'), ('starter_cloud', 'Starter Cloud'), ('wordpress_pro', 'WordPress Pro'), ('business_cloud', 'Business Cloud'), ('agency_turbo', 'Agency Turbo'), ('performance_max', 'Performance Max'), ('flask_addon', 'Flask Add-on')], max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_slug',
            field=models.CharField(choices=[('free', 'Free'), ('test_plan', 'Starter Trial'), ('launch_lite', 'Launch Lite'), ('starter_cloud', 'Starter Cloud'), ('wordpress_pro', 'WordPress Pro'), ('business_cloud', 'Business Cloud'), ('agency_turbo', 'Agency Turbo'), ('performance_max', 'Performance Max'), ('flask_addon', 'Flask Add-on')], db_index=True, default='free', max_length=32),
        ),
    ]
