# Generated by Django 5.2.14 on 2026-05-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('postgres', 'PostgreSQL'), ('redis', 'Redis')], default='postgres', max_length=20)),
                ('name', models.CharField(help_text='Logical DB name', max_length=64)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('password_encrypted', models.TextField(blank=True, help_text='Fernet ciphertext (same key as env vars)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_instances', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='databases_dbinstance_project_name_uniq')],
            },
        ),
    ]
