# Generated by Django 5.2.14 on 2026-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliate_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateapplication',
            name='message',
            field=models.TextField(help_text='Why do you want to become an affiliate? How will you promote Krizn?', max_length=1000),
        ),
    ]
