# Generated by Django 5.0.14 on 2026-06-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_partner_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
