# Generated by Django 5.2.14 on 2026-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTlsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='default', max_length=64, unique=True)),
                ('acme_contact_email', models.EmailField(blank=True, max_length=254)),
                ('cert_resolver_name', models.CharField(default='letsencrypt', max_length=64)),
                ('traefik_acme_json_path', models.CharField(blank=True, help_text='Server path to acme.json (chmod 600). Documented for ops; not used by Django yet.', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'platform TLS / ACME',
                'verbose_name_plural': 'platform TLS / ACME',
            },
        ),
    ]
