# Generated by Django 5.2.14 on 2026-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_quotaconfig_max_projects_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaconfig',
            name='max_projects',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
