# Generated by Django 5.2.14 on 2026-05-13 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=253)),
                ('record_type', models.CharField(default='A', max_length=10)),
                ('target_ip', models.CharField(max_length=45)),
                ('cloudflare_record_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'fqdn'), name='dnsmanager_project_fqdn_uniq')],
            },
        ),
    ]
