# Generated by Django 5.2.14 on 2026-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellorder',
            name='items_snapshot',
            field=models.JSONField(help_text='Cart items at time of purchase: [{product_id, name, qty, unit_price}]'),
        ),
    ]
