# Generated by Django 5.0.14 on 2026-05-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0002_assetoptimizationrun_sites_scanned'),
        ('projects', '0007_websiteoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompressionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('trigger', models.CharField(choices=[('upload', 'Upload'), ('scheduled', 'Scheduled')], default='upload', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('images_found', models.PositiveIntegerField(default=0)),
                ('images_optimized', models.PositiveIntegerField(default=0)),
                ('bytes_saved', models.BigIntegerField(default=0)),
                ('ultra_images_optimized', models.PositiveIntegerField(default=0)),
                ('ultra_bytes_saved', models.BigIntegerField(default=0)),
                ('total_bytes_saved', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_compression_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
