# Generated by Django 5.0.14 on 2026-05-16 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_completed', models.PositiveSmallIntegerField(default=0, help_text='Last finished wizard step (1=name, 2=project, 3=upload).')),
                ('skipped', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set after first successful deployment (or skip).', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user onboarding',
                'verbose_name_plural': 'user onboarding',
            },
        ),
    ]
