# Generated by Django 5.0.14 on 2026-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('getting_started', 'Getting Started Guide'), ('upsell_offer', 'Upsell Offer'), ('order', 'Order Email'), ('renewal', 'Renewal Email'), ('affiliate_training', 'Affiliate Training'), ('abandoned_cart', 'Abandoned Cart'), ('learning_academy', 'Learning Academy'), ('partner', 'Partner Email'), ('upsell', 'Upsell Email'), ('review_collection', 'Review Collection')], db_index=True, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='Use {{placeholder}} syntax. See docs for available placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='us2.smtp.mailhostbox.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.EmailField(default='admin@krizn.com', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(default='admin@krizn.com', max_length=255)),
                ('from_name', models.CharField(default='Krizn', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Config',
                'verbose_name_plural': 'SMTP Configs',
            },
        ),
    ]
